blank_issues_enabled: false
contact_links:
  - name: Atlas-ERP Documentation
    url: https://github.com/KB01111/Atlas-erp-clean/wiki
    about: Check our documentation for answers to common questions
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
