# Temporal dynamic configuration for development
# This file is referenced in the docker-compose.yml configuration

frontend.enableClientVersionCheck:
  - value: true
    constraints: {}

history.defaultActivityRetryPolicy:
  - value:
      initialIntervalInSeconds: 1
      maximumIntervalInSeconds: 100
      maximumAttempts: 3
      backoffCoefficient: 2
    constraints: {}

history.defaultWorkflowRetryPolicy:
  - value:
      initialIntervalInSeconds: 1
      maximumIntervalInSeconds: 100
      maximumAttempts: 3
      backoffCoefficient: 2
    constraints: {}

system.enableReadFromES:
  - value: false
    constraints: {}

limit.maxIDLength:
  - value: 255
    constraints: {}

# PostgreSQL specific settings
system.sql.pluginName:
  - value: postgres
    constraints: {}

system.sql.databaseName:
  - value: temporal
    constraints: {}

system.sql.connectAddr:
  - value: postgres:5432
    constraints: {}

system.sql.connectProtocol:
  - value: tcp
    constraints: {}

system.sql.user:
  - value: temporal
    constraints: {}

system.sql.password:
  - value: temporal
    constraints: {}

system.sql.maxConns:
  - value: 20
    constraints: {}

system.sql.maxIdleConns:
  - value: 20
    constraints: {}

system.sql.maxConnLifetime:
  - value: 1h
    constraints: {}
